dist: trusty
before_script:
  - sudo add-apt-repository "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main" -y
  - sudo apt-get update -q
  - sudo apt-get install -y --force-yes g++ libz-dev libedit-dev llvm-3.8-dev

language: rust
rust:
  - stable
  - beta
  - nightly
