before_script:
  - sudo add-apt-repository "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty main" -y
  - sudo apt-get update -q
  - sudo apt-get install -y g++ libz-dev libedit-dev

language: rust
rust:
  - stable
  - beta
  - nightly
